version: "3.9"

services:
  # Uncomment services as needed
  
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: mcp_agui
  #     POSTGRES_PASSWORD: mcp_agui_password
  #     POSTGRES_DB: mcp_agui_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  redis_data: